### ISSUE TITLE
https://spacetravel.simhub.online/ is IP not found...

### ISSUE THREAD

**Issue by Merovex** [nathangeffen/space-travel#4]
```
This site can’t be reached www.simhub.online’s server IP address could not be found.
Try:

Checking the connection
Checking the proxy, firewall, and DNS configuration
Running Windows Network Diagnostics
ERR_NAME_NOT_RESOLVED
```

**Comment by nathangeffen** [comment]
Hi

Sorry, I changed name servers and internet host over the weekend and
proceeded to make a complete mess of it. I intend to fix it in the next day
or two. Really sorry about that.

Regards
Nathan

**Comment by Merovex** [comment]
Timed it perfect, then. :) I moved to Google Domains a while back, and host on Github. The reassignment is wicked fast (5m between polling). Just glad it's not gone for good.

Have a good week. Would you mind closing this when you're done so I'll know to go back? Love the site.

**Comment by nathangeffen** [comment]
Thanks. Yes definitely will notify here once it's up.

**Comment by nathangeffen** [comment]
http://spacetravel.simhub.online is up. Unfortunately the https site is not yet working. In frantically trying to fix the problem I tried to get too many certificates from  Lets Encrypt and exceeded the weekly limit for number of certificate requests. In a few days I'll request again and bring the https version back up. Sorry about that.

**Comment by nathangeffen** [comment]
https://spacetravel.simhub.online is working fine again.

**Comment by Merovex** [comment]
Awesome, thanks!
